services:
  app:
    image: golang:1.24
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD:-1234}
      - TEST_DB_HOST=db
      - TEST_DB_PORT=5432
      - TEST_DB_USER=postgres
      - TEST_DB_PASSWORD=${DB_PASSWORD:-1234}
    working_dir: /app
    volumes:
      - ./app:/app
      - app-go-vol:/go
    depends_on:
      - db
  db:
    image: postgres:17.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=stock
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-1234}
    volumes:
      - db-vol:/var/lib/postgresql/data
volumes:
  app-go-vol:
  db-vol:
