openapi: "3.0.3"
info:
  title: Stock Tool API
  version: "1.0.0"
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8080
    description: Local development server
security: []
paths:
components:
